# Generated by Django 2.0.5 on 2018-07-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=200, verbose_name='密码')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('image', models.ImageField(max_length=200, upload_to='user/images', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
