# Generated by Django 2.0.5 on 2018-07-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('btype', models.IntegerField(choices=[(0, '美食'), (1, '科技'), (2, '教育'), (3, '娱乐'), (4, '财经'), (5, '影视'), (6, '体育')], verbose_name='类型')),
                ('summary', models.TextField(default='', verbose_name='概要')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='文章内容')),
                ('cnt', models.IntegerField(default=0, verbose_name='点击量')),
                ('publish_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.User')),
            ],
        ),
    ]
