# Generated by Django 2.0.5 on 2018-07-13 08:31

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='评论')),
                ('reply_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Blob', verbose_name='博客')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.User', verbose_name='用户')),
            ],
        ),
    ]
